/***************************************************************************************************************************
 * @file: /Users/jason/Sites/cotf/src/react-app-env.d.ts
 * -----------------------------------------------------------------------------------------------------------------------------------------------
 * @description: This file contains a reference directive for TypeScript to include type definitions from the react-scripts package.
 * ---------------------------------------------------------------------------------------------------------------------------------------------
 * @functionality: Instructs TypeScript to include the type definitions from the 'react-scripts' package, which is part of Create React App. This ensures TypeScript understands the types and structures used by react-scripts.
 * ---------------------------------------------------------------------------------------------------------------------------------------------
 * Created by: Jason McCoy
 * Created on: 12/30/2023
 * ---------------------------------------------------------------------------------------------------------------------------------------------
 * Last Updated by: Jason McCoy
 * Last Updated on: 01/04/2024
 * ---------------------------------------------------------------------------------------------------------------------------------------------
 * Changes made: 
 *     - Initial file setup with reference to react-scripts types.
 * ---------------------------------------------------------------------------------------------------------------------------------------------
 * Notes: 
 *     - This file is typically auto-generated by Create React App and doesn't usually require modifications.
 *     - It's crucial for TypeScript-based React projects as it provides the necessary type declarations for a smooth development experience.
 ***************************************************************************************************************************/

/// <reference types="react-scripts" />
